# Generated by Django 3.2.3 on 2021-08-11 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=12)),
                ('date_created', models.DateField()),
                ('last_updated', models.DateField()),
                ('is_archived', models.BooleanField(default=False)),
                ('is_trashed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
